### ISSUE TITLE
error load sd1.5 model

### ISSUE THREAD

**Issue by guahunyo** [nullquant/ComfyUI-BrushNet#1]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/18573180/64189824-db00-4f28-adf0-721bde4d27cd)

**Comment by guahunyo** [comment]
![0OEQIXNILX`XWI7BS4@40W9](https://github.com/nullquant/ComfyUI-BrushNet/assets/18573180/f8bb7927-6612-4cd8-a0f4-5c51bc050e7f)
![7$M3W6 1S36V0 9~ 1JG%{Q](https://github.com/nullquant/ComfyUI-BrushNet/assets/18573180/c530a82b-75c3-44bb-ba1c-701b9e0e33ec)

**Comment by nullquant** [comment]
Thank you for a solution. Updated.
As for second error - it seems you have problem with GitHub connection. I added file which `diffusers` tried to load to repo, should work now.

**Comment by guahunyo** [comment]
> Thank you for a solution. Updated.谢谢你的解决方案。更新。 As for second error - it seems you have problem with GitHub connection. I added file which `diffusers` tried to load to repo, should work now.至于第二个错误 - 似乎您的 GitHub 连接有问题。我添加了 `diffusers` 尝试加载到存储库的文件，现在应该可以工作了。

its ok now,  thank you
