### ISSUE TITLE
Hello author, could you please test it yourself when you have free time? When reading a batch of video frames, if it exceeds 30 frames, the memory will be insufficient. Whether it is an inpaint or an outpaint, please test it yourself and fix it

### ISSUE THREAD

**Issue by meetedlike** [nullquant/ComfyUI-BrushNet#100]
Hello author, could you please test it yourself when you have free time? When reading a batch of video frames, if it exceeds 30 frames, the memory will be insufficient. Whether it is an inpaint or an outlier, please test it yourself and fix it
<img width="1499" alt="brushnet1" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/157203596/66d136b6-b037-4353-a42c-55920deba2ca">
<img width="1056" alt="brushnet2" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/157203596/9d70a914-6dda-4374-b4ed-0442a4cdc66d">
<img width="1119" alt="brushnet3" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/157203596/1c9cb2b3-f704-4598-a23c-3f37908861cd">

**Comment by nullquant** [comment]
This is workflow with 50 images and it takes about 17 Gb of VRAM at maximum:

![Screenshot from 2024-05-19 11-48-33](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/a21f39ba-1345-470b-97df-4000373af2ee)

But it depends, of course, on many factors including other models, such as SAM and DINO, which you can do in separate workflow, but most of all on image resolution. In any case you can do it in several batches of less images.

**Comment by meetedlike** [comment]
Compared with the workflow you sent, I roughly understand why my 30 images got OOM. The reason is that the video frames I uploaded have a resolution of 1080 * 1920, while you used 512 * 512. Thank you for your reply. Your attitude towards the problem has made me feel that 1. You really want to do a good job with this plugin. 2. You also feel that you are willing to handle and solve the problem. Thank you. I will test it again when I have time, and also hope that you can optimize it when you have time. I still hope to make an outward extension that can handle one minute of video. If I find any problems, I will submit them. Thank you

**Comment by nullquant** [comment]
@meetedlike 
I have found a solution for you. You can use Evolved Sampling from [AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved.git):

![Screenshot from 2024-05-23 22-02-59](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/eb65c44c-4a51-414d-ab90-415accb2419d)

In `Context Options` set context_length to number of images which can be loaded into VRAM. Images will be processed in chunks of this size.
