### ISSUE TITLE
What exactly does RAUNet do? Can anyone help me understand?

### ISSUE THREAD

**Issue by lzhfdwu007** [nullquant/ComfyUI-BrushNet#101]
The latest example I saw inserted a
RAUNet node, but I don't quite understand the role of this node?
Can you give me a little explanation on the application of this node to make it easier for me to understand?

**Comment by lzhfdwu007** [comment]
There are 4 parameters in total
du_start
du_end
xa_start
xa_end
To be honest, I'm a little confused about what they control respectively.

**Comment by lzhfdwu007** [comment]
直接运行基础示例的话，是可以控制大尺寸图像生成过多的重复目标。
但是还是不明白具体的参数对于结果会有怎么样的影响

**Comment by lzhfdwu007** [comment]
If you run the basic example directly, you can control the generation of excessive duplicate targets in large-size images.
But I still don’t understand how the specific parameters will affect the results.

**Comment by nullquant** [comment]
Did you read [this](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/RAUNET.md)?

**Comment by lzhfdwu007** [comment]
> Did you read [this](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/RAUNET.md)? Should I elaborate more on its parameters?

Thank you. I really didn’t see it before, but now I understand~~~THX
