### ISSUE TITLE
Can this support inpainting model?

### ISSUE THREAD

**Issue by davidchenhs** [nullquant/ComfyUI-BrushNet#103]
!!! Exception during processing!!! Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 14, 16, 16] to have 9 channels, but got 14 channels instead
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2206, in sample_adv
    return super().sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 713, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 537, in process_latent_image
    samples = KSamplerAdvanced().sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler,
  File "D:\ComfyUI-aki-v1.3\nodes.py", line 1378, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "D:\ComfyUI-aki-v1.3\nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-StableSR\nodes.py", line 75, in hook_sample
    return original_sample(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 313, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\comfy\sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 761, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\model_patch.py", line 113, in modified_sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 650, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 629, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 534, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 618, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 272, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 616, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 619, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 258, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
    return calc_cond_batch_original_tiled_diffusion_7be40c4f(model, conds, x_in, timestep, model_options)
  File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 216, in calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\model_patch.py", line 51, in brushnet_model_function_wrapper
    method(unet, xc, t, to, control)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 1003, in brushnet_forward
    input_samples, mid_sample, output_samples = brushnet_inference(x, timesteps, transformer_options)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 916, in brushnet_inference
    return brushnet(x,
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 830, in forward
    sample = self.conv_in_condition(brushnet_cond)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 14, 16, 16] to have 9 channels, but got 14 channels instead

When I use the inpainting model I get this error

**Comment by nullquant** [comment]
BrushNet was trained and is intended to use with SD1.5 and SDXL models, so you should use them or models based on them.

**Comment by davidchenhs** [comment]
Can this support efficiency nodes? Error will be reported when brushnet is used together with the efficiency loader.

> BrushNet was trained and is intended to use with SD1.5 and SDXL models, so you should use them or models based on them.

**Comment by nullquant** [comment]
![Screenshot from 2024-05-24 10-09-59](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/d4445195-9fbf-47d0-b1cc-60b7850ed5d0)

What error do you have?

**Comment by davidchenhs** [comment]
Nothing!Thx!

**Comment by JS1989git** [comment]
> !!! Exception during processing!!! Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 14, 16, 16] to have 9 channels, but got 14 channels instead Traceback (most recent call last): File "D:\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "D:\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "D:\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2206, in sample_adv return super().sample(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 713, in sample samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler, File "D:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 537, in process_latent_image samples = KSamplerAdvanced().sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler, File "D:\ComfyUI-aki-v1.3\nodes.py", line 1378, in sample return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise) File "D:\ComfyUI-aki-v1.3\nodes.py", line 1314, in common_ksampler samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, File "D:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-StableSR\nodes.py", line 75, in hook_sample return original_sample(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample raise e File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations. File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 313, in motion_sample return orig_comfy_sample(model, noise, *args, **kwargs) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_reference.py", line 47, in refcn_sample return orig_comfy_sample(model, *args, **kwargs) File "D:\ComfyUI-aki-v1.3\comfy\sample.py", line 37, in sample samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 761, in sample return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\model_patch.py", line 113, in modified_sample return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 650, in sample output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 629, in inner_sample samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 534, in sample samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 618, in sample_dpmpp_2m_sde denoised = model(x, sigmas[i] * s_in, **extra_args) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 272, in **call** out = self.inner_model(x, sigma, model_options=model_options, seed=seed) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 616, in **call** return self.predict_noise(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 619, in predict_noise return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 258, in sampling_function out = calc_cond_batch(model, conds, x, timestep, model_options) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion.patches.py", line 4, in calc_cond_batch return calc_cond_batch_original_tiled_diffusion_7be40c4f(model, conds, x_in, timestep, model_options) File "D:\ComfyUI-aki-v1.3\comfy\samplers.py", line 216, in calc_cond_batch output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\model_patch.py", line 51, in brushnet_model_function_wrapper method(unet, xc, t, to, control) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 1003, in brushnet_forward input_samples, mid_sample, output_samples = brushnet_inference(x, timesteps, transformer_options) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 916, in brushnet_inference return brushnet(x, File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 830, in forward sample = self.conv_in_condition(brushnet_cond) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward return self._conv_forward(input, self.weight, self.bias) File "D:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward return F.conv2d(input, weight, bias, self.stride, RuntimeError: Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 14, 16, 16] to have 9 channels, but got 14 channels instead
> 
> When I use the inpainting model I get this error

I've gotten this same error... Out of curiosity if anyone happens to know, what is the deal with this? Are inpaint models not based one 1.5/xl? Why does it not want to accept inpaint models?
