### ISSUE TITLE
Error occurred when executing BrushNetLoader

### ISSUE THREAD

**Issue by rezponze** [nullquant/ComfyUI-BrushNet#108]
Hi! 

The node installed without problems and the models are places as your instructions. 
But when loading and running the BrushNet_SDXL_basic.json workflow gives me this error. Any tips? I'm running on a 3060 with 12gb VRAM. 

Error occurred when executing BrushNetLoader:

CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 105, in brushnet_loading
    brushnet_model = load_checkpoint_and_dispatch(
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\venv\lib\site-packages\accelerate\big_modeling.py", line 598, in load_checkpoint_and_dispatch
    device_map = infer_auto_device_map(
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\venv\lib\site-packages\accelerate\utils\modeling.py", line 1121, in infer_auto_device_map
    max_memory = get_max_memory(max_memory)
  File "F:\StabilityMatrix\Data\Packages\ComfyUI-dev\venv\lib\site-packages\accelerate\utils\modeling.py", line 825, in get_max_memory
    _ = torch.tensor([0], device=i)

**Comment by nullquant** [comment]
Try to pass the --disable-cuda-malloc parameter to comfy when you start it.

**Comment by rezponze** [comment]
--disable-cuda-malloc worked. Thanks!

**Comment by HSJDZNM** [comment]
![屏幕截图 2024-06-07 091731](https://github.com/nullquant/ComfyUI-BrushNet/assets/131422417/d3fb7c28-8c09-4e19-86b5-c408e44f5df2)

I added "--disable-cuda-malloc" and it still didn't work, but I was able to use it yesterday and not this morning. Above isa screenshot of my console and interface log

**Comment by HSJDZNM** [comment]
I added "--disable-cuda-malloc" and it still didn't work, but I was able to use it yesterday and not this morning. Below isa screenshot of my console and interface log
![屏幕截图 2024-06-07 091731](https://github.com/nullquant/ComfyUI-BrushNet/assets/131422417/39e5e590-e53a-400f-ade6-fb16e4a3b5b2)

**Comment by HSJDZNM** [comment]
My video card has more than 40 gigabytes of memory, and I don't think it's a problem with my video card

**Comment by HSJDZNM** [comment]
My graphics card has over 40GB of VRAM, so I don't think the issue is with my graphics card.

**Comment by HSJDZNM** [comment]
My graphics card has 80GB of VRAM, so I don't think it's an issue with my graphics card. I'm running it on GPU 0
![屏幕截图 2024-06-07 092524](https://github.com/nullquant/ComfyUI-BrushNet/assets/131422417/bc8ce9a1-2fd0-40be-aae1-d5aaea5615c4)

**Comment by HSJDZNM** [comment]
No worries, a restart can solve my weird problem.
