### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 52Hz-p** [nullquant/ComfyUI-BrushNet#111]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

**Comment by nullquant** [comment]
Could you please post a full ComfyUI log?

**Comment by icesun963** [comment]
[comfyui_8190.log](https://github.com/user-attachments/files/15856436/comfyui_8190.log)
same error

**Comment by nullquant** [comment]
I can not produce this error on my side, so I tried to repair it but not sure about result. Update nodes and give it a try. If the error persists post ComfyUI log please.

**Comment by icesun963** [comment]
thx, it works very well.

**Comment by icesun963** [comment]
[comfyui_8190.log](https://github.com/user-attachments/files/15913936/comfyui_8190.log)
powerpaint works ,but  brushnet still error.

**Comment by nullquant** [comment]
Log is empty

**Comment by icesun963** [comment]
[comfyui_8190.log](https://github.com/user-attachments/files/15924330/comfyui_8190.log)
Sorry, my mistake, I'll upload it again.

**Comment by nullquant** [comment]
This error was produced in controlnet ComfyUI module. It is not due to BrushNet. What about example workflows with BrushNet, do they work in your setup?

**Comment by icesun963** [comment]
I did some tests and found that cn was missing and not working in my environment. It should be some problems caused by the update of comfyui. Thank you very much for your reply.

**Comment by nullquant** [comment]
You are welcome!
