### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by SEEEYOU121** [nullquant/ComfyUI-BrushNet#112]
一旦运行到这个模块就出现这个错误TypeError: Failed to fetch
![QQ图片20240610195355](https://github.com/nullquant/ComfyUI-BrushNet/assets/167508116/15c304f0-8390-4b2a-be2f-0ea408898f32)

**Comment by nullquant** [comment]
Could you please post full ComfyUI log?

**Comment by yami-Jeremy** [comment]
I had the same problem, here is my workflow
[powerpaint_workflow.json](https://github.com/user-attachments/files/15832992/powerpaint_workflow.json)

**Comment by nullquant** [comment]
Again, could you please post full ComfyUI log?

**Comment by yami-Jeremy** [comment]
> Again, could you please post full ComfyUI log?


Here it is:
Error occurred when executing BrushNetLoader:

Unknown BrushNet model

File "/home/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 71, in brushnet_loading
raise Exception("Unknown BrushNet model")

**Comment by yami-Jeremy** [comment]
This is the location of the model file

![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/81603645/36d8d6a5-bec9-4872-9f1c-7bd6f0131b32)


This is a screenshot of my ComfyUI interface
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/81603645/bca798d2-6bdd-4924-897c-1c3398c02970)


I added some logs to the source code, and the output is shown in the figure
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/81603645/b4db5a3b-7e65-4bf7-a606-c322082ea79c)

**Comment by nullquant** [comment]
So, it is not a valid BrushNet model.

Here is how it should be (look at the sizes):
![Screenshot from 2024-06-15 19-07-22](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/1701d770-2fb5-472f-8d80-083c7b4f3443)
