### ISSUE TITLE
CutFor Inpaint: Mask is bigger than provided dimensions

### ISSUE THREAD

**Issue by yongsuH** [nullquant/ComfyUI-BrushNet#117]
I got an error "CutFor Inpaint: Mask is bigger than provided dimensions" when I'm trying to inpaint a video feeding the CutForInpaint node with a bunch of images and masks.
The mask and the image are the same size however it still throws this error.

**Comment by nullquant** [comment]
When you use CutForInpaint node, it cuts a part of image with provided dimension. But that part should be bigger than masked area which is not in your case. So, it is not mask but masked area is bigger than provided dimensions. You just need to increase dimensions (width, height) in CutForInpaint node.
