### ISSUE TITLE
Inconsistent Inpainting Results with `v_prediction` Models

### ISSUE THREAD

**Issue by linanwx** [nullquant/ComfyUI-BrushNet#118]
Hello,

Firstly, thank you for creating BrushNet; it's one of the most natural inpainting tools I've used. However, I've encountered an issue when using BrushNet with `v_prediction` models. The inpainted images often appear incorrect or blurry. Is this due to an incompatibility with `v_prediction`? Any guidance or solutions would be greatly appreciated.

Thank you!

**Comment by nullquant** [comment]
Thank you for the kind words, but I only adapted BrushNet for ComfyUI. You can reach authors of BrushNet [here](https://github.com/TencentARC/BrushNet).

As for `v_prediction` models, yes, it is possible that they are incompatible. BrushNet was trained with base models (`runwayml/stable-diffusion-v1-5` and `stabilityai/stable-diffusion-xl-base-1.0`). It is possible to train BrushNet with other models but it requires good hardware.
