### ISSUE TITLE
Cant git clone the code. 

### ISSUE THREAD

**Issue by Kimthanh27** [nullquant/ComfyUI-BrushNet#119]
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 6739 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

D:\COMFYUI\ComfyUI\custom_nodes>

**Comment by nullquant** [comment]
It is probably some network problems. You can try to switch to HTTP 1.1:
`git config --global http.version HTTP/1.1`
`git clone https://github.com/nullquant/ComfyUI-BrushNet`
`git config --global http.version HTTP/2`

**Comment by ralfleeb** [comment]
tried that - still:

PS C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes> git config --global http.version HTTP/1.1
PS C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes> git clone https://github.com/nullquant/ComfyUI-BrushNet.git
Cloning into 'ComfyUI-BrushNet'...
remote: Enumerating objects: 559, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
error: 513 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

tried this several times

**Comment by nullquant** [comment]
Ok, so you can't git clone the repo. You can try various solutions, for example, [here](https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining). Or you can just download [zip](https://github.com/nullquant/ComfyUI-BrushNet/archive/refs/heads/main.zip) from GitHub page and unzip it in the `custom_nodes\ComfyUI-BrushNet` directory.
