### ISSUE TITLE
vram leakage?

### ISSUE THREAD

**Issue by cheezecrisp** [nullquant/ComfyUI-BrushNet#127]
I've noticed that every time I switch brushnet/sd models and run, the vram usage increases further. I wonder if this is normal or if there is a vram leakage issue?

**Comment by nullquant** [comment]
I just did a couple of tests. ComfyUI has a complicated system of memory management. It seems to me that VRAM was not totally freed up after using BrushNet nodes but there is no increase. So after several switches BrushNet SD1.5 -> BrushNet SDXL -> SDXL the memory usage stabilized. The resulting values are depend on total VRAM of your GPU and ComfyUI startup options.

**Comment by cheezecrisp** [comment]
OK, may be something wrong with my os or python envirment, thanx for checking.
