### ISSUE TITLE
Does PowerPaint support SDXL? Or will it?

### ISSUE THREAD

**Issue by 925-Studio** [nullquant/ComfyUI-BrushNet#128]
Hi, thank you for make these wonderful nodes. But I found if I choose SDXL model then PowerPaint shows error. I have not found any related information on the net so I come here to ask. Hope you can share some tips. Thank you for your time, really appreciate.

**Comment by nullquant** [comment]
Thank you for kind words. Unfortunately PowerPaint is only compatible with SD 1.5 and I didn't hear [the authors](https://github.com/open-mmlab/PowerPaint) are going to train it with SDXL.

**Comment by 925-Studio** [comment]
Not problem. With your nodes and these models, SD 1.5 works just fine. The best inpaint in ComfyUI I have ever used. Thank you!
