### ISSUE TITLE
Can it be used with ipadapter ?

### ISSUE THREAD

**Issue by lvdougao1** [nullquant/ComfyUI-BrushNet#13]
![screenshot-20240419-105633](https://github.com/nullquant/ComfyUI-BrushNet/assets/89889954/7a3282fc-08cf-4e24-9b5e-2d7ac8649c81)
It doesn't seem to be working.

**Comment by nullquant** [comment]
Yes, indeed. I will look into it.

**Comment by nullquant** [comment]
The problem with IP Adapter that in ComfyUI it is a patch to model which is executed at sampling stage. So, when model is converted for use with BrushNet the patch is lost. There is a possibility to add simple IP Adapter to BrushNet pipeline but all complexity and infrastructure of IP Adapter v2 will be lost. I think to solve this problem the BrushNet Pipeline code should be converted to ComfyUI PatchedModel.

**Comment by acumenleo** [comment]
how about Instantid ? is it the same as the IP Adapter?

**Comment by nullquant** [comment]
Yes it should.
