### ISSUE TITLE
Mask not working?

### ISSUE THREAD

**Issue by mi8m** [nullquant/ComfyUI-BrushNet#137]
The ksampler's output (with brushnet) is fried, as if the entire image got passed through low denoise and not just the mask

**Comment by nullquant** [comment]
Could you please post you workflow?

**Comment by mi8m** [comment]
Actually, it seemed like a model issue. Seems to be working as intended, just did a more in depth settings test after seeing your examples.

**Comment by GGGabc** [comment]
yes, you are right.If you set step to 1, this problem is obvious
