### ISSUE TITLE
SD1.5 text encoder model link broken in readme

### ISSUE THREAD

**Issue by Fus3n** [nullquant/ComfyUI-BrushNet#139]
The link https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder is broken, looks like runwayml removed the models, I haven't tried the Powerpaint version yet, is this necessary? if so then looks like it needs to be fixed, I don't have the model.

**Comment by nullquant** [comment]
Yes, Runway [deleted](https://www.aibase.com/news/11434) their HuggingFace and GitHub repos. I've updated link to some mirrors.
