### ISSUE TITLE
Error occurred when executing BrushNet:  Image and mask should be the same size

### ISSUE THREAD

**Issue by liaceboy** [nullquant/ComfyUI-BrushNet#140]
Error occurred when executing BrushNet:

Image and mask should be the same size

**Comment by liaceboy** [comment]
Size inconsistencies, resolved

**Comment by nullquant** [comment]
So as it says: the image and mask should be of the same size.

**Comment by bramvera** [comment]
i'm using the same size and still got the error

**Comment by nullquant** [comment]
Post a full log of Comfyui, please.

**Comment by bramvera** [comment]
> Post a full log of Comfyui, please.

thanks for the heads up, It’s all fixed now! I reset the conda env and reinstalled everything. Looks like one of the libraries was the culprit.
