### ISSUE TITLE
The model placed in extra_model_paths is not readable

### ISSUE THREAD

**Issue by EnoshSAGIRI** [nullquant/ComfyUI-BrushNet#145]
The model placed in `extra_model_paths` is not readable, the configuration in `extra_model_paths.yaml` is correct, and I have placed the model in the folder, but the loader is not able to read it, according to the README document, it is placed under ‘models/inpaint According to the README document, it's under `models/inpaint` and `models/clip`, but the `PowerPaintCLIP Loader` and the `BrushNet Loader` both show undefind.
My `extra_model_paths.yaml` configuration looks like this:

> a111:
>    base_path: E:/
>    inpaint: models/inpaint
>    clip: models/clip

ComfyUI console shows 

> Adding extra search path inpaint E:/models/inpaint
> Adding extra search path clip E:/ models/clip

indicating that the configured paths are fine.
And once I copied these files to the comfyUI directory, the Loader was able to read them.

**Comment by nullquant** [comment]
Can you post your `extra_model_paths.yaml`, all of it? Where is your ComfyUI base directory? Also can you post ComfyUI starting log?

**Comment by EnoshSAGIRI** [comment]
I found the problem, I shouldn't use `a111` but `comfyui `in my `extra_model_paths.yaml`.I was able to find other models using `a111` before, but this should be a coincidence
