### ISSUE TITLE
为什么我不能用ipadpter

### ISSUE THREAD

**Issue by Fred10086** [nullquant/ComfyUI-BrushNet#15]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/166596625/5dc49e45-b7c1-4f5e-b1b1-4d2209abbed5)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/166596625/1069495a-2497-4397-bcbb-00aae88f1a2e)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/166596625/2d7eef1b-a669-4c42-a59e-2f9c813b1c09)
这三个我都试了全报错了
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/166596625/7c9bbcd8-b8da-4f7f-8b30-bad1ab7a4532)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/166596625/e2ae1157-b774-424a-8893-f25ae8191219)
我用的都是1.5模型

**Comment by Fred10086** [comment]
希望能和最新ipadpater v2 能用在一起就好了

**Comment by nullquant** [comment]
Well, first of all these are not my nodes. The problem with IP Adapter that in ComfyUI it is a patch to model which is executed at sampling stage. So, when model is converted for use with BrushNet the patch is lost. There is a possibility to add simple IP Adapter to BrushNet pipeline but all complexity and infrastructure of IP Adapter v2 will be lost. There is no working solution yet.
