### ISSUE TITLE
segmentation_mask_brushnet_ckptrandom_mask_brushnet_ckpt These two models have been downloaded several times with the same name and size. What is the problem

### ISSUE THREAD

**Issue by meetedlike** [nullquant/ComfyUI-BrushNet#16]

**Comment by nullquant** [comment]
You should download place model file `random_mask_brushnet_ckpt/diffusion_pytorch_model.safetensors` inside `models\inpaint\brushnet` folder. Nodes does not download anything. 

Could you be more specific? Do you have errors?
