### ISSUE TITLE
too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by claireliu14** [nullquant/ComfyUI-BrushNet#17]
I use [this](https://civitai.com/models/125651/indoors30v15mdbz) model to do outpainting and get the following error message:

```
Error occurred when executing BrushNetInpaint:

too many indices for array: array is 1-dimensional, but 2 were indexed

File "/home/osense/Documents/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/osense/Documents/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/osense/Documents/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/osense/Documents/ComfyUI/custom_nodes/ComfyUI-BrushNet/brushnet_nodes.py", line 203, in brushnet_inpaint
mask_image = 1.*(mask_image>250)[:,:,np.newaxis]
~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
```

<img width="1182" alt="Screenshot 2024-04-23 at 11 43 05 AM" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/6873073/67fe263e-0468-41e4-8859-8c8bb4a68be6">

  
The input image and mask are as shown in the figure:
<img width="1180" alt="Screenshot 2024-04-23 at 11 43 22 AM" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/6873073/0b1566db-c237-4c7d-b0dd-52d1b297b58d">

Does anyone have suggestions for me to modify the workflow?

**Comment by nullquant** [comment]
Okay, I just fixed the error. Try it out.

**Comment by claireliu14** [comment]
Thank you. This issue was solved.
