### ISSUE TITLE
BrushNet for SDXL model

### ISSUE THREAD

**Issue by Shuvo001** [nullquant/ComfyUI-BrushNet#18]
Is there have any way or possibilities to use BurshNet model with SDXL instead of SD1.5?

**Comment by nullquant** [comment]
There are no BrushNet model weights for SDXL yet. According to [this](https://github.com/TencentARC/BrushNet/issues/20) they will be soon.

**Comment by newxhy** [comment]
据说有了

**Comment by newxhy** [comment]
google drive里面新增的两个带SDXL的文件夹，里面的模型是SDXL的？

**Comment by nullquant** [comment]
Yes, working on it
