### ISSUE TITLE
brushnet_example_inpaint_ella.json workflow can not be used with the tencent official Ella project together

### ISSUE THREAD

**Issue by wujm424606** [nullquant/ComfyUI-BrushNet#19]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/38379474/f00f3338-af13-406f-99bd-8c25d0a75f54)
This is website of tencent official ELLA project:
https://github.com/TencentQQGYLab/ComfyUI-ELLA
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/38379474/8c22e567-640f-4ca5-88aa-45c9178f5eac)
They can not be connected

**Comment by nullquant** [comment]
These are not my nodes, it is another project.
