### ISSUE TITLE
Brushnet import failed

### ISSUE THREAD

**Issue by tristan22mc** [nullquant/ComfyUI-BrushNet#20]
![Screenshot 2024-04-23 165815](https://github.com/nullquant/ComfyUI-BrushNet/assets/98059631/6cc38e85-035f-4a62-9820-a5b139f3782c)
![Screenshot 2024-04-23 165735](https://github.com/nullquant/ComfyUI-BrushNet/assets/98059631/ad0624b9-69ce-4d31-b33c-562664da8323)

I saw in another thread you had mentioned you had fixed imports. Just wanted to post this to show imports seem to still be having issues. I downloaded both through comfy manager and also the instructions located in the readme and both seemed to fail

**Comment by nullquant** [comment]
Could you please post ComfyUI starting logs with error?

**Comment by Liteyn** [comment]
Same error

Error:
[WinError 1314] Клиент не обладает требуемыми правами: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'C:\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to C:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: C:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\__init__.py", line 1, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint#, TestNode
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 17, in <module>
    from .brushnet.brushnet import BrushNetModel
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet\brushnet.py", line 20, in <module>
    from .unet_2d_blocks import (
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet\unet_2d_blocks.py", line 26, in <module>
    from diffusers.models.resnet import (
ImportError: cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet' (C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\resnet.py)

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet module for custom nodes: cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet' (C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\resnet.py)

**Comment by nullquant** [comment]
`diffusers` version should be 0.27.0 or higher. Try to update it.

**Comment by Liteyn** [comment]
> `diffusers` version should be 0.27.0 or higher. Try to update it.

C:\ComfyUI_windows_portable\ComfyUI>pip install --upgrade diffusers[torch]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: diffusers[torch] in c:\users\николай\appdata\roaming\python\python310\site-packages (0.27.2)

**Comment by nullquant** [comment]
You use portable win ComfyUI. So your local python installation `c:\users\николай\appdata\roaming\python\python310\site-packages` is different from ComfyUI's `C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages`. You need to update python embedded library:
`C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-BrushNet\requirements.txt`

**Comment by Liteyn** [comment]
> Вы используете портативный Win ComfyUI. Таким образом, ваша локальная установка Python `c:\users\николай\appdata\roaming\python\python310\site-packages`отличается от установки ComfyUI `C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages`. Вам необходимо обновить встроенную библиотеку Python: `C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\requirements.txt`

Thank you very much

**Comment by nullquant** [comment]
You are welcome :)
