### ISSUE TITLE
For single brushnet: `brushnet_conditioning_scale` must be type `float`.

### ISSUE THREAD

**Issue by MingZeY** [nullquant/ComfyUI-BrushNet#21]
The following error occurred when I was using two brushnet nodes
For single brush net: ` brush net conditional scale ` must be type ` float `

It happened in brushnet/pipeline_brushnet. py:638

**Comment by nullquant** [comment]
Could you please post your workflow, so I can reproduce this error? What parameter did you use for a `scale` in `BrushNetInpaint` node?
