### ISSUE TITLE
PowerPaint v2

### ISSUE THREAD

**Issue by monika1900** [nullquant/ComfyUI-BrushNet#23]
Is the PowerPaint v2 model compatible? You can find it in this GitHub repository: https://github.com/open-mmlab/PowerPaint

The model features an architecture akin to BrushNet and delivers remarkable inpainting performance.

**Comment by nullquant** [comment]
I plan to implement it. I am working on non-`diffusers` native ComfyUI version now. I think it will be ready in a couple of days. Then it will be possible to use IP Adapter v2 and all other ComfyUI nodes with BrushNet. After that I am going to implement PowerPaint v2.

**Comment by monika1900** [comment]
Thanks!

**Comment by newxhy** [comment]
那么现在brushnet模型加载器里面，可以选择PowerPaint v2，意思是已经支持了？

**Comment by nullquant** [comment]
PowerPaint is ready.
