### ISSUE TITLE
SDXL model release, any update？

### ISSUE THREAD

**Issue by DENG-XC** [nullquant/ComfyUI-BrushNet#24]
Hi, thanks you for your hard work to implement brushnet in comfyui!!! 
The SDXL model has been release, any update to compatible with SDXL model? or I can just download the SDXL model and use it as usual?
https://github.com/TencentARC/BrushNet

**Comment by nullquant** [comment]
I am working on it

**Comment by aartikov** [comment]
@DENG-XC @nullquant 
Is it implemented already?
