### ISSUE TITLE
Can it be used with controlnet? 

### ISSUE THREAD

**Issue by zhei87** [nullquant/ComfyUI-BrushNet#25]
I added controlnet, and it didn't seem to work.

**Comment by nullquant** [comment]
Yes, it works. Check examples, please.

**Comment by zhei87** [comment]
> Yes, it works. Check examples, please.

After the update on April 29, I tried the workflow in the example, and there seems to be a problem. Instead of redrawing the mask area, it redraws the whole picture.
![1111](https://github.com/nullquant/ComfyUI-BrushNet/assets/5158014/4636e645-e209-4680-bcbe-dfd5c8ff596a)
![2222](https://github.com/nullquant/ComfyUI-BrushNet/assets/5158014/1a50ac47-9145-452a-aada-da5803a1e2ff)

**Comment by nullquant** [comment]
It seems BrushNet is not working at your ComfyUI install at all. Could you please post ComfyUI console output? Thank you.

**Comment by zhei87** [comment]
The console did not output any errors. I am normal on another device. After inspection, I found that it is related to the "FreeU-Advanced" extension. I deleted it, everything is normal.
