### ISSUE TITLE
RuntimeError: The size of tensor a (448) must match the size of tensor b (450) at non-singleton dimension 1

### ISSUE THREAD

**Issue by leol333** [nullquant/ComfyUI-BrushNet#34]
When I'm running Blend Inpaint, most of the time is fine, but sometimes with some images, I encounter this error: 

!!! Exception during processing!!! The size of tensor a (448) must match the size of tensor b (450) at non-singleton dimension 1
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 275, in blend_inpaint
    ret.append(original * (1.0 - blurred_mask[0][0][:,:,None]) + result.to(original.device) * blurred_mask[0][0][:,:,None])
                  
                  

I'm not sure where went wrong, please help, Thank you!

**Comment by nullquant** [comment]
Could you please send me an example of images which generate this error, can't replicate it on my side.

**Comment by NeedsMoar** [comment]
I think comfy's internal stuff always rounds image sizes to multiples of 8 so latent generation works well, maybe this doesn't?  Just a guess.

**Comment by nullquant** [comment]
Patched it. I hope it will work.
