### ISSUE TITLE
feature request - support playground or cosxl/edit?

### ISSUE THREAD

**Issue by whmc76** [nullquant/ComfyUI-BrushNet#36]
i know it maybe not so easy,but really need a inpaint solution , brushnet is the best inpaint tech for now

**Comment by nullquant** [comment]
Unfortunately I've encountered quite a problem while implementing SDXL version of BrushNet. It seems to be connected with different VAE implementation in `diffusers` and `comfy` but up to now I got some bizarre color change in images. Working on it. Also the quality of BrushNet XL is lower so don't expect much, please.

**Comment by nullquant** [comment]
Technically BrushNet nodes can be used with any model of SD1.5 and SDXL structure. So there is no errors when you use both Playground and CosXL with BrushNet. But the resulting images are totally wrong. BrushNet was trained with other models so it can't be helped. You can see all the details [here](https://github.com/TencentARC/BrushNet).
