### ISSUE TITLE
模型下载地址里没有1.5的模型，只有一个json

### ISSUE THREAD

**Issue by 52Hz-p** [nullquant/ComfyUI-BrushNet#42]
![Uploading Snipaste_2024-05-02_17-16-28.png…]()

**Comment by nullquant** [comment]
Could you please translate, and the image link is broken.

**Comment by 52Hz-p** [comment]
> 能翻译一下吗，图片链接失效了。

就是我下载random_mask_brushnet_ckpt后里面只有一个json文件，没有safetensors文件了，好像您的这个brushnet不能与inpaint同时使用是吗

**Comment by nullquant** [comment]
https://drive.google.com/drive/folders/1fqmS1CEOvXCxNWFrsSYd_jHYXxrydh1n?usp=drive_link

![Screenshot from 2024-05-02 12-43-16](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/df84b812-eebc-496c-ad69-c59d1cd53f32)

**Comment by 52Hz-p** [comment]
> https://drive.google.com/drive/folders/1fqmS1CEOvXCxNWFrsSYd_jHYXxrydh1n?usp=drive_link
> 
> ![2024-05-02 12-43-16 截图](https://private-user-images.githubusercontent.com/81931994/327385111-df84b812-eebc-496c-ad69-c59d1cd53f32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDM0MDYsIm5iZiI6MTcxNDY0MzEwNiwicGF0aCI6Ii84MTkzMTk5NC8zMjczODUxMTEtZGY4NGI4MTItZWViYy00OTZjLWFkNjktYzU5ZDFjZDUzZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiODlkYjY5NjE1NWZjZmE5ZjI4OTc3Mjk5MTU0NjkxZmVhNTdmOWMzYjg2NTVjOWFmNTdlZGEyNDhlZDEyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7opaU5xme-z_BXKeg8wV_RQLQuqRGsSV8oDaw0Ea5U)

感谢您的帮助，不过我刚才发现了一个冲突，是一个叫做[ComfyUI-Crystools的插件，他提供一个动态的工作流程进度显示，但是您的插件和他的会有冲突，当安装后，这个进度就会一直显示为100.。当然这个冲突无关紧要，您的这个插件真的很棒

**Comment by nullquant** [comment]
Well, the progress bar doesn't work, yes.

**Comment by 52Hz-p** [comment]
> 好吧，进度条不起作用，是的。

是的，您是否后面会解决这种冲突，还是说是环境依赖冲突

**Comment by nullquant** [comment]
I am not sure the problem is on BrushNode side, but ok. I will look into it after I implement PowerPaint.

**Comment by nullquant** [comment]
Should work now.
