### ISSUE TITLE
I need to add --force-fp16

### ISSUE THREAD

**Issue by Kwisss** [nullquant/ComfyUI-BrushNet#43]
congrats on getting this working in comfyui!

I own a 1660 super, and to run this plugin I need to add --force-fp16, 
just so you know!

ps. a witch told me marigold and other add-ons added a fancy switch.

**Comment by Kwisss** [comment]
in other extensions it can result in black pictures, with your extension I get this error:
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and Half

I hacked a solution together myself:

I added/changed this to brushnet.py
dtype = torch.float16 if use_fp16 else torch.float32 if is_mps else torch.float64

and this to brushnetnodes.py

"use_fp16": ("BOOLEAN", {"default": False}),

and 

brushnet(x.to(brushnet.device).half() if use_fp16 else x.to(brushnet.device) in brushnet nodes

and I added the use_fp16 variable to the applicable functions.

**Comment by nullquant** [comment]
Thanks for the information. I will probably change main branch to use float16 everywhere, BrushNet was trained with that precision.

**Comment by nullquant** [comment]
Some ppl still have problems with float16, so I added a dtype switch to BrushNet loader. Check it out if you like.
