### ISSUE TITLE
Question : 2nd Latent output

### ISSUE THREAD

**Issue by yushan777** [nullquant/ComfyUI-BrushNet#44]
Can you provide more information on the 2nd latent output from the brushnet node?  It (and the negative output) don't appear in the example images in the readme.md

**Comment by nullquant** [comment]
I am working on PowerPaint implementation. These outputs will be needed there. They are conditioning, not latents. You should delete Brushnet node from workflow, then add it again and you will see them correctly. Now they are just copied from input, so you can feed them directly to KSampler to lessen the number of connecting lines.
