### ISSUE TITLE
Error occurred when executing BrushNet:'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by liffeng** [nullquant/ComfyUI-BrushNet#47]
![微信图片_20240504011507](https://github.com/nullquant/ComfyUI-BrushNet/assets/128386052/62db8ec8-23bb-47d6-86fb-ff37231660e1)

**Comment by nullquant** [comment]
What nodes for CLIP Text encoding do you use? I updated the code, so there should be no errors like that, but that 'pooled_output' is actually needed for correct BrushNet inference. ComfyUI original nodes `CLIP Text Encode (Prompt)` and `CLIPTextEncodeSDXL` both have correct output.

**Comment by liffeng** [comment]
It's solved! The reason is that I used an efficiency node, and it worked fine when I switched to a normal node
