### ISSUE TITLE
After using brushnet model diffusion, reusing the default model diffusion will not be available

### ISSUE THREAD

**Issue by yolain** [nullquant/ComfyUI-BrushNet#48]
After using brushnet model diffusion, reusing the default model diffusion will not be available.
![屏幕截图 2024-05-04 014544](https://github.com/nullquant/ComfyUI-BrushNet/assets/73304135/742e438c-53eb-44ed-96fb-dcc59ae0b602)
My python is pool. I tried to reset model.model.diffusion_model.forward to original after the first diffusion. But it seems to end up going to brushnet_inference.
![屏幕截图 2024-05-04 015222](https://github.com/nullquant/ComfyUI-BrushNet/assets/73304135/b2d0b7db-bae4-41f7-b25a-33d6cb745155)

**Comment by nullquant** [comment]
What do you want do accomplish by this workflow? 

I've already got similar issues, so I wonder. My main goal for native incorporation of BrushNet to ComfyUI was to pair it (BrushNet) to existing models **before** BrushNet application: IP Adapter, LoRA, CotrolNet, you name it. But I never thought what to do with the model after inference. 

As for reusing the original model - it should work, update the code.

**Comment by yolain** [comment]
Thank you for your reply.for example,I want to do tiled diffusion upscale the image after brushnet diffusion in the same workflow，but it not working.

**Comment by nullquant** [comment]
Please, see upscale example in readme.
