### ISSUE TITLE
how to lader model

### ISSUE THREAD

**Issue by cardenluo** [nullquant/ComfyUI-BrushNet#5]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/133877069/41771df9-732a-4b4a-982f-81885d508636)
only read the document ,but model

**Comment by nullquant** [comment]
![Screenshot from 2024-04-13 11-50-10](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/baa77c7d-67f2-497d-b642-cb2de2684d75)
This is how folder inside `models` should look like. Sorry, can't understand what problem you have. Could you describe it more?

**Comment by zejacky** [comment]
Hello @cardenluo 
I have following structure (Windows), and it works.
───inpaint
│   └───brushnet
│       ├───random_mask_brushnet_ckpt
│       │       config.json
│       │       diffusion_pytorch_model.safetensors
│       │
│       └───segmentation_mask_brushnet_ckpt
│               config.json
│               diffusion_pytorch_model.safetensors

**Comment by cardenluo** [comment]
@nullquant  @zejacky  thanks.
Since the link to download the model cannot be opened, I searched for these two models and configuration files on the hub and put them into the corresponding file structure. However, the UI interface cannot recognize the model. Maybe these two models are different from the models on the corresponding nodes, so they cannot be  recognized?
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/133877069/c51caeee-6d9c-483a-9e83-12f7ab263cd5)

**Comment by zejacky** [comment]
@cardenluo 
I was downloading the files from google drive without issues, the link is provided at  https://github.com/nullquant/ComfyUI-BrushNet?tab=readme-ov-file
You need to download the 2 mentioned folders. After you have 2 zip files, unzip it into the local folders:
random_mask_brushnet_ckpt / segmentation_mask_brushnet_ckpt. 
**attention**: The files will have all the same name! The name need to be like that on the image from nullquant or see my last post.

**Comment by cardenluo** [comment]
thanks

**Comment by nullquant** [comment]
I have just downloaded `config.json` and `diffusion_pytorch_model.safetensors` into `./models/inpaint/brushnet/test/' folder from [Sanster/brushnet_random_mask](https://huggingface.co/Sanster/brushnet_random_mask/tree/main). And it is working just fine. Remember, you need to click on down arrow near file name to download model.
![Screenshot from 2024-04-14 19-37-56](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/df7a28e1-c2a3-4245-9de2-0cffb80babbe)

**Comment by nullquant** [comment]
Check new version, please

**Comment by nullquant** [comment]
Last version does not need `config.json`.
