### ISSUE TITLE
As a large company, it is advisable to create an output. The current input is very mature and there are many methods to implement it

### ISSUE THREAD

**Issue by meetedlike** [nullquant/ComfyUI-BrushNet#52]
As a large company, it is advisable to create an output. The current input is very mature and there are many methods to implement it

**Comment by nullquant** [comment]
I don't understand. What are you trying to say? Who is a large company?

**Comment by meetedlike** [comment]
Sorry, I have imagined you as a big company. Your inpaint is very good. If you have the time and technical ability, I think you can consider doing an outpaint and batch processing, combined with tools like animatediff. Thank you for your work

**Comment by nullquant** [comment]
Thank you for a suggestion, I will think about it.

**Comment by meetedlike** [comment]
Thank you, I really didn't think about it. You can take my suggestion and it was done so quickly. I saw some friends in the group using the nodes you created to expand the image, and the effect was very good. I hope you continue to work hard and make better nodes.

**Comment by nullquant** [comment]
Thank you for a good words :)

**Comment by nullquant** [comment]
Image batch is done. I also paired BrushNet with AnifateDiff but the result are meh... They both try to move UNet sampling in different directions, so the result is mess. I think it is possible to use BrushNet as a pre or post video processor to change objects, but right now it lacks consistency - every image in batch calculated differently.
