### ISSUE TITLE
I used the Inpaint node, and a size error occurred. I wonder if you can help me solve this problem?

### ISSUE THREAD

**Issue by Ahcool123** [nullquant/ComfyUI-BrushNet#54]
There was this error message.：The size of tensor a (1216) must match the size of tensor b (64) at non-singleton dimension 1

The picture I use is size：1216x1216.
![Uploading 001.png…]()

**Comment by chenxianshen1998** [comment]
Error occurred when executing BrushNet:

PowerPaint model is not yet supported

File "D:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 179, in model_update
raise Exception("PowerPaint model is not yet supported")

**Comment by nullquant** [comment]
@Ahcool123 Could you please post ComfyUI log?
