### ISSUE TITLE
PowerPaint model is not yet supported

### ISSUE THREAD

**Issue by chenxianshen1998** [nullquant/ComfyUI-BrushNet#55]
Error occurred when executing BrushNet:  PowerPaint model is not yet supported  File "D:\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 179, in model_update raise Exception("PowerPaint model is not yet supported")

**Comment by nullquant** [comment]
You tried to load PowerPaint model. I am working on PowerPaint implementation, but it is not done.

**Comment by chenxianshen1998** [comment]
> You tried to load PowerPaint model. I am working on PowerPaint implementation, but it is not done.

Is there a workflow?

**Comment by nullquant** [comment]
It will be when it will be done.

**Comment by nullquant** [comment]
PowerPaint is ready.
