### ISSUE TITLE
help！ Error occurred when executing KSamplerAdvanced Inspire:  'step'

### ISSUE THREAD

**Issue by jokero3answer** [nullquant/ComfyUI-BrushNet#57]
[Diagnostics-1714835195.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15210073/Diagnostics-1714835195.log)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/28fdf55f-9d82-4109-a1ad-571b64bf500c)
[BrushNet_SDXL_basic研究中.json](https://github.com/nullquant/ComfyUI-BrushNet/files/15210089/BrushNet_SDXL_basic.json)

**Comment by nullquant** [comment]
This is KSampler from https://github.com/ltdrdata/ComfyUI-Inspire-Pack , right? Can you please post ComfyUI log with error?

**Comment by jokero3answer** [comment]
[Diagnostics-1714877423.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15211595/Diagnostics-1714877423.log)
@nullquant This is a log file. Take a look. Thank you.

**Comment by jokero3answer** [comment]
Is it because the a1111 weight parsing method of generating images is not currently supported,?

**Comment by nullquant** [comment]
Yes, it is due to custom KSampler. I will try to think up something.

**Comment by jokero3answer** [comment]
Okay, thanks, because a1111 weight resolution way to generate the image quality will be better, please you can support!

**Comment by nullquant** [comment]
Upgrade and give it a try - should work now.

**Comment by jokero3answer** [comment]
[Diagnostics-1714965047.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15215558/Diagnostics-1714965047.log)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/f32e70ff-a34a-478a-9cfd-36de59704e14)
@nullquant I've updated and re-run all of them, and there are new errors reported, you can see the logs in this one

**Comment by jokero3answer** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/4f080066-dcdc-4a76-805d-ff6f61dc06a4)
Now the basic sdxl upload mask and raw sampler is reporting this error too!

**Comment by nullquant** [comment]
Could you post full error log, not just start of it?

**Comment by jokero3answer** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/31f5f79a-1263-45b4-8455-8c0de040e417)
@nullquant here

**Comment by nullquant** [comment]
It does not seems to correlate with KSampler patch, but anyway. Update and try it now.

**Comment by jokero3answer** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/9a85f1b4-d3a5-4fbb-8691-74f2dbb0f6b2)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/8081dbd3-d306-4397-aff4-1fee3b7e9427)

**Comment by jokero3answer** [comment]
[workflow.json](https://github.com/nullquant/ComfyUI-BrushNet/files/15218101/workflow.json)
[Diagnostics-1714982180.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15218113/Diagnostics-1714982180.log)
It's all up to date, but still this error, is it because of my calculation precision settings

**Comment by jokero3answer** [comment]
I'm not sure if anyone else is reporting this error, which I found when I completely reinstalled on another computer

Error occurred when executing KSampler:

mat1 and mat2 must have the same dtype, but got Float and Half

**Comment by nullquant** [comment]
Please update, your commit 8cbe9d8, current 21536e

**Comment by jokero3answer** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/cb04592f-f440-4191-b8ac-f381e068b411)
I tried it a couple times and it came up as a black picture

**Comment by jokero3answer** [comment]
![Uploading image.png…]()

**Comment by nullquant** [comment]
So, no more mixed types error? Do you get that same blank image with ComfyUI's KSampler? And could you post a log, please?

**Comment by jokero3answer** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/b9e263b0-2df9-4e4f-8b39-ce913dea73d5)

**Comment by jokero3answer** [comment]
[Diagnostics-1714990612.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15219364/Diagnostics-1714990612.log)
Check it out and thank you so much for your patience!

**Comment by nullquant** [comment]
Could you please try a thing for me, because I can't reproduce this error on my end? Download a VAE from here [`vae-ft-mse-840000-ema-pruned.safetensors`](https://huggingface.co/stabilityai/sd-vae-ft-mse-original/tree/main). Add `Load VAE` node to workflow and connect it to BrushNet and VAE Decode, then run. Thank you!

**Comment by jokero3answer** [comment]
I'll try it.

**Comment by nullquant** [comment]
The problem with blank image may be due to VAE float16 [NaN error](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/13908). I patched the code but would like to check if it is indeed VAE.

**Comment by jokero3answer** [comment]
Ok, I'll try mounting vae separately now

**Comment by nullquant** [comment]
It should be checked on your other computer where you got blank images. Thank you.

**Comment by jokero3answer** [comment]
ok, I'll test it tomorrow at the company computer experiment, thanks!
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/47685f28-fd43-4dd9-a469-ef76bfbebbbf)

a1111 does look great with this node repaint!

**Comment by nullquant** [comment]
Thank you! :)
