### ISSUE TITLE
BrushnetPipeline & BrushNetInpaint  were not found

### ISSUE THREAD

**Issue by gudaolang** [nullquant/ComfyUI-BrushNet#58]
![Snipaste_2024-05-04_23-59-32](https://github.com/nullquant/ComfyUI-BrushNet/assets/8936798/9ffb955e-eae8-4e10-b68b-331e39496099)
VAE dtype: torch.bfloat16
### ComfyUI Revision: 2160 [72508a8d] | Released on '2024-05-04'
No errors during startup...
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/8936798/83565221-4105-47fa-b8fa-43d25f24fa4e)

**Comment by nullquant** [comment]
There are no such nodes in this repository.

**Comment by K-O-N-B** [comment]
same problems here.

**Comment by K-O-N-B** [comment]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/152141077/073986f4-902c-4083-a6dd-3770cad4ffa3)

**Comment by cdmusic2019** [comment]
@K-O-N-B  You can just re-download the workflow, the original workflow will have this problem, download the '.json' file.

**Comment by nullquant** [comment]
Oh, I see, it is workflows from a one of the first versions. Please update the nodes and workflows.

**Comment by gudaolang** [comment]
@nullquant  @K-O-N-B  thx,  this issue can be closed now. (*￣︶￣)
