### ISSUE TITLE
how to load LoRA ?

### ISSUE THREAD

**Issue by huan085128** [nullquant/ComfyUI-BrushNet#6]
I can't find the node loading lora. and also no support for comfyui's lora loading mode

**Comment by huan085128** [comment]
Negative prompt don't seem to be supported either.

**Comment by nullquant** [comment]
Yes, I think it is possible, but not with current implementation, of course. I will look into it, but give me several days as a lot of code should be reviewed and rewritten.

**Comment by nullquant** [comment]
Check new version, please

**Comment by huan085128** [comment]
> Check new version, please

Thank you very much. I'll try

**Comment by nullquant** [comment]
Last version supports both LoRA and negative prompts.
