### ISSUE TITLE
([640, 640, 1, 1])

### ISSUE THREAD

**Issue by kongyingzhe** [nullquant/ComfyUI-BrushNet#61]
![2024_05_05_20_22 53 拷贝](https://github.com/nullquant/ComfyUI-BrushNet/assets/150431287/f914a8f0-1771-4e90-8594-e8a1e0a9ba09)

This error message indicates a problem occurred when executing the brushnet_model_loader function. Specifically, the error message states that there was an attempt to set a tensor with a shape of torch.Size([640, 640]) into a weight tensor with a shape of torch.Size([640, 640, 1, 1]), which appears to be incorrect.        How should this problem be solved?

**Comment by nullquant** [comment]
You are trying to load a wrong BrushNet file. Check what you downloded and choosed in loader.

**Comment by kongyingzhe** [comment]
非常感谢，我检查一下
