### ISSUE TITLE
Nice job! But stil need to fix some problems.

### ISSUE THREAD

**Issue by kelvinyoung** [nullquant/ComfyUI-BrushNet#64]
e.g when the human face area is too small in the whole picture, then excuting the inpainting, the face will be slightly redraw too, and also BrushNet maybe too powerful to creat new strange things especially in the peripheral areas.
![截屏2024-05-06 15 03 50](https://github.com/nullquant/ComfyUI-BrushNet/assets/1706234/51b72427-dd73-4dd9-af10-51d0fa0a4ff6)

**Comment by inferno46n2** [comment]
> e.g when the human face area is too small in the whole picture, then excuting the inpainting, the face will be slightly redraw too, and also BrushNet maybe too powerful to creat new strange things especially in the peripheral areas. ![截屏2024-05-06 15 03 50](https://private-user-images.githubusercontent.com/1706234/328101833-51b72427-dd73-4dd9-af10-51d0fa0a4ff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTgxMzUsIm5iZiI6MTcxNTAxNzgzNSwicGF0aCI6Ii8xNzA2MjM0LzMyODEwMTgzMy01MWI3MjQyNy1kZDczLTRkZDktYWYxMC01MWQwZmEwYTRmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTc1MDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZkMTNkOTYyZjlhYmUwNTg2ODRmMWNlY2MyYzkwMzEyMDk1ZWRlZGNmNzI0NThjYzc2NmNkYzdlZjBiY2M0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bLJ9IkbCXJdvV2SoS0TFNMa_Gmu1WO6S22_JGenl8BY)

be sure to use the roundmask node on your input mask. This fixed most of my problems. BrushNET seems to only want pure white or pure black

**Comment by inferno46n2** [comment]
Would be a useful check to have built into the brushnet loader. A mask check for non 255 or 0 values.

**Comment by nullquant** [comment]
That's right, BrushNet only use 1.0 in mask (or 255). So, you suggest to turn all non zero values to max (255 or 1)? It is easy to do, I just never though it is needed.

**Comment by inferno46n2** [comment]
> That's right, BrushNet only use 1.0 in mask (or 255). So, you suggest to turn all non zero values to max (255 or 1)? It is easy to do, I just never though it is needed.

Yes you couple simply implement what Kijai's "RoundMask" mask node is doing such that if it fails the check on the mask it fixes it rather than just running 

https://github.com/kijai/ComfyUI-KJNodes/blob/main/nodes/mask_nodes.py

**Comment by kelvinyoung** [comment]
> BrushNet is not a silver bullet and sometimes you need to adapt it. There is `scale` parameter in node to change BrushNet's "strength", also you can blend inpaint to leave non-masked area unchanged, see examples.

Thx.I do use blend inpaint node to try to fix, but it seems that after the blending, the non-masked area is not as clear as the output image.

**Comment by kelvinyoung** [comment]
> > e.g when the human face area is too small in the whole picture, then excuting the inpainting, the face will be slightly redraw too, and also BrushNet maybe too powerful to creat new strange things especially in the peripheral areas. ![截屏2024-05-06 15 03 50](https://private-user-images.githubusercontent.com/1706234/328101833-51b72427-dd73-4dd9-af10-51d0fa0a4ff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTgxMzUsIm5iZiI6MTcxNTAxNzgzNSwicGF0aCI6Ii8xNzA2MjM0LzMyODEwMTgzMy01MWI3MjQyNy1kZDczLTRkZDktYWYxMC01MWQwZmEwYTRmZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTc1MDM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZkMTNkOTYyZjlhYmUwNTg2ODRmMWNlY2MyYzkwMzEyMDk1ZWRlZGNmNzI0NThjYzc2NmNkYzdlZjBiY2M0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bLJ9IkbCXJdvV2SoS0TFNMa_Gmu1WO6S22_JGenl8BY)
> 
> be sure to use the roundmask node on your input mask. This fixed most of my problems. BrushNET seems to only want pure white or pure black

Ok,thx.I try a binary mask.
