### ISSUE TITLE
It's strange, with 840000 lora is still black picture, is it my computer which piece of the setting problem

### ISSUE THREAD

**Issue by jokero3answer** [nullquant/ComfyUI-BrushNet#66]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/6bb6962d-0544-4933-9b97-7cac309ffe3c)
[Diagnostics-1715051942.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15228985/Diagnostics-1715051942.log)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/c85eb3b7-9f0c-459f-8a36-a654211dbd59)

**Comment by jokero3answer** [comment]
@nullquant

**Comment by jokero3answer** [comment]
I've realized that my default Vincennes chart is black as well，haha
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/6923ea01-e4cc-4cbc-b6a2-21172f21745a)

**Comment by jokero3answer** [comment]
[Diagnostics-1715062183.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15231065/Diagnostics-1715062183.log)
@nullquant

**Comment by nullquant** [comment]
I added a dtype switch to BrushNet loader. Try to change it to different values.

**Comment by jokero3answer** [comment]
ok,thank you
