### ISSUE TITLE
Why was the entire image redrawn? BrushNet_basic workflow

### ISSUE THREAD

**Issue by samen168** [nullquant/ComfyUI-BrushNet#67]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/31786234/c53db61d-ed8b-4583-9ac3-4b42ed45a2cb)

**Comment by BNP1111** [comment]
blend inpaint PLZ

**Comment by nullquant** [comment]
BrushNet is not working. Post your ComfyUI log, please.

**Comment by samen168** [comment]
The logs are gone, rolled back the version and was able to complete the repaint
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/31786234/23bbeadd-3a32-49bc-986b-5acf3b556c72)

**Comment by nullquant** [comment]
That is probably due to precision change. Some setups have problems with that. I am working on it right now.

**Comment by nullquant** [comment]
I just added dtype switch to BrushNet Loader node. Try it now, change if you have problems.

**Comment by chflame163** [comment]
> I just added dtype switch to BrushNet Loader node. Try it now, change if you have problems.

Looks like the issue persists

**Comment by nullquant** [comment]
Can you post a log, please?

**Comment by BNP1111** [comment]
> I just added dtype switch to BrushNet Loader node. Try it now, change if you have problems.我刚刚在 BrushNet Loader 节点中添加了 dtype 开关。现在就试试吧，如果有问题，请更改。

solove my problem

**Comment by chflame163** [comment]
> Can you post a log, please?

I update the plugin to latest commit, and use example/BrushNet_SDXL_basic.json，result is as follows：

```
(base) PS E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet> git log
commit afe771460159e835e50d53506f9b8ecfaa489cb8 (HEAD -> main, origin/main, origin/HEAD)
Author: nullquant <merlinkun@yandex.ru>
Date:   Tue May 7 18:00:20 2024 +0300

    dtype switch
```

![Uploading 微信图片_20240508003413.png…]()


```
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight', 'clip_g.logit_scale']
#47 [CheckpointLoaderSimple]: 9.98s
#58 [LoadImage]: 0.06s
BrushNet model type: Loading SDXL
BrushNet model file: E:\ComfyUI-work\ComfyUI_windows_portable\ComfyUI\models\inpaint\brushnet\segmentation_mask_brushnet_ckpt_sdxl_v0\diffusion_pytorch_model.safetensors
BrushNet SDXL model is loaded
#45 [BrushNetLoader]: 1.38s
Requested to load SDXLClipModel
Loading 1 new model
#49 [CLIPTextEncode]: 1.23s
#50 [CLIPTextEncode]: 0.06s
Base model type: SDXL
BrushNet image, torch.Size([1, 1024, 1024, 3])
Requested to load AutoencoderKL
Loading 1 new model
BrushNet CL: image_latents shape = torch.Size([2, 4, 128, 128]) interpolated_mask shape = torch.Size([2, 1, 128, 128])
#61 [BrushNet]: 1.77s
Requested to load SDXL
Loading 1 new model
  0%|                                                                                                                                       | 0/20 [00:00<?, ?it/s]BrushNet inference: sample torch.Size([2, 4, 128, 128]) , CL torch.Size([1, 5, 128, 128])
BrushNet inference: do_classifier_free_guidance is True
BrushNet inference: sample torch.Size([2, 4, 128, 128]) , CL torch.Size([2, 5, 128, 128])
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:11<00:00,  1.67it/s]
#52 [KSampler]: 12.81s
#54 [VAEDecode]: 0.69s
#12 [PreviewImage]: 0.13s
Prompt executed in 28.25 seconds
```

**Comment by chflame163** [comment]
> @chflame163 Ohh, now I see it! Please, change `ent_at` parameter in BrushNet node to 100, for example.

Yes , I modified here as you said and now it works fine. Thanks.

**Comment by nullquant** [comment]
Due to this parameter BrushNet applied only to 1st and second iteration steps only. BTW, playing with these you can achieve some interesting results. I will update examples, sorry for inconvenience.

**Comment by chflame163** [comment]
> Due to this parameter BrushNet applied only to 1st and second iteration steps only. BTW, playing with these you can achieve some interesting results. I will update examples, sorry for inconvenience.

Interesting, looking forward to updating example：）Thank you excllent job!

**Comment by samen168** [comment]
> @chflame163 Ohh, now I see it! Please, change `ent_at` parameter in BrushNet node to 100, for example.
'end_at' 100 It's good

**Comment by chflame163** [comment]
> Due to this parameter BrushNet applied only to 1st and second iteration steps only. BTW, playing with these you can achieve some interesting results. I will update examples, sorry for inconvenience.

What does ```end _ at``` mean here? I see that this number can be adjusted very high, but I have tried 100 to 1000 and there is no difference in the final image.

**Comment by nullquant** [comment]
This parameter sets end step at which to apply BrushNet. Try set it a bit less than your `steps` in KSampler.

**Comment by chflame163** [comment]
> This parameter sets end step at which to apply BrushNet. Try set it a bit less than your `steps` in KSampler.

Got it, Thanks.
