### ISSUE TITLE
powerpaint_v2 object removal problem

### ISSUE THREAD

**Issue by tanglup** [nullquant/ComfyUI-BrushNet#68]
powerpaint_v2 uses ordinary sd1.5 large models and cannot remove human even if they are removed.
![4f](https://github.com/nullquant/ComfyUI-BrushNet/assets/160642431/bd94cfdd-f780-4eea-a1e8-488461eacb26)
Where to download model.fp16 from
![44fa](https://github.com/nullquant/ComfyUI-BrushNet/assets/160642431/25826cc9-af4c-42dd-af19-3e47eba8d670)

**Comment by nullquant** [comment]
model.fp16.safetensors should be taken from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder).

Yes, I am too disappointed a little about object removal. It is often hard to completely remove the object, especially if it is at the front. Try to add `human` to negative prompt and describe empty scene, like `empty rock over horizon `, like here:

![Screenshot from 2024-05-07 12-26-40](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/161ac247-9c84-4068-9218-ee86732146fe)

**Comment by tanglup** [comment]
> [model.fp16.safetensors 应该从这里](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder)获取。
> 
> 是的，我对物体移除感到有点失望。通常很难完全移除该物体，特别是如果它位于前面。尝试添加`human`到否定提示并描述空场景，例如`empty rock over horizon`，这里：
> 
> ![截图自 2024-05-07 12-26-40](https://private-user-images.githubusercontent.com/81931994/328467768-161ac247-9c84-4068-9218-ee86732146fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODc3MjQsIm5iZiI6MTcxNTA4NzQyNCwicGF0aCI6Ii84MTkzMTk5NC8zMjg0Njc3NjgtMTYxYWMyNDctOWM4NC00MDY4LTkyMTgtZWU4NjczMjE0NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDRiZjQyODdiMTQzNWIzNWJkMWI3Y2E4NDBkMzk3YjdlZjI4NTRjZWM1ZDI3ZjA3NThjOWY0MjE2ZDhkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rT88OQMqJ5HTx5C0wMnwmLaEfNGfMOJ6GnI6j45nuT0)

Thank you very much for the reply

**Comment by nullquant** [comment]
You are welcome! :)

**Comment by yatoubusha** [comment]
> model.fp16.safetensors should be taken from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder).
> 
> Yes, I am too disappointed a little about object removal. It is often hard to completely remove the object, especially if it is at the front. Try to add `human` to negative prompt and describe empty scene, like `empty rock over horizon`, here:
> 
> ![Screenshot from 2024-05-07 12-26-40](https://private-user-images.githubusercontent.com/81931994/328467768-161ac247-9c84-4068-9218-ee86732146fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjM0MzEsIm5iZiI6MTcxNjM2MzEzMSwicGF0aCI6Ii84MTkzMTk5NC8zMjg0Njc3NjgtMTYxYWMyNDctOWM4NC00MDY4LTkyMTgtZWU4NjczMjE0NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA3MzIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMWNmNDNmNDk1NjhlMjhiOGUzMTNiMzdiNTdiNDdlMWY3NDlhYTU3MmFjNWUxNmIyZWQ1NjExMjNkYTYyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YUIY_ghEeZeNzOr3FgNZhqiKWxOPvJUQ9rwaRPuQr04)

下载这个文件后，应该放在哪个文件夹下呢？这个powerpaint只支持1.5的模型吗？

**Comment by nullquant** [comment]
For PowerPaint you should download three files. Both diffusion_pytorch_model.safetensors and pytorch_model.bin from [here](https://huggingface.co/JunhaoZhuang/PowerPaint_v2/tree/main/PowerPaint_Brushnet) should be placed in your models/inpaint folder.

Also you need SD1.5 text encoder model model.fp16.safetensors from [here](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main/text_encoder). It should be placed in your models/clip folder.

Yes, only SD1.5.
