### ISSUE TITLE
powerpaint workflow cant use with contronet

### ISSUE THREAD

**Issue by BNP1111** [nullquant/ComfyUI-BrushNet#71]
powerpaint workflow cant use with contronet

**Comment by nullquant** [comment]
![Screenshot from 2024-05-07 19-55-34](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/657eb72c-e38c-40cc-aedf-685f960e89db)

Why not?

**Comment by BNP1111** [comment]
could u PLZ test canny

**Comment by BNP1111** [comment]
my problem,sorry for that, closed
