### ISSUE TITLE
'force_hooks',maybe clip issue?

### ISSUE THREAD

**Issue by laogu1027** [nullquant/ComfyUI-BrushNet#74]
Error occurred when executing BrushNetLoader:

load_checkpoint_and_dispatch() got an unexpected keyword argument 'force_hooks'

File "E:\ai\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ai\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\ai\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ai\ComfyUI\custom_nodes\ComfyUI-BrushNet\brushnet_nodes.py", line 103, in brushnet_loading
brushnet_model = load_checkpoint_and_dispatch(

**Comment by nullquant** [comment]
It means you try to update wrong python installation. Try to find out which python installation used by ComfyUI. For example you can open `main.py` in ComfyUI base folder and add `print(sys.executable)` at line 47. Then start ComfyUI and look at console output.

**Comment by kunkun-zhu** [comment]
I also encountered the same problem. Have you solved it？

**Comment by nullquant** [comment]
It is a problem with your installation. Update nodes, then create a workflow like that:

![Screenshot from 2024-06-03 11-13-29](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/195a09bb-2370-45b1-b2f4-bff30351a8a9)

Write `"pip list"` in Terminal node. Execute and check CoumfyUI log: it will list all packages with their version in your ComfyUI installation. `accelerate` package should have version 0.29 or more.
