### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jokero3answer** [nullquant/ComfyUI-BrushNet#75]
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/e8b489d2-79b4-421e-b7a5-ef71bf457474)
@nullquant

**Comment by jokero3answer** [comment]
The first two steps of sampling are normal, then it turns into a goat

**Comment by jokero3answer** [comment]
[Diagnostics-1715145389.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15244105/Diagnostics-1715145389.log)

**Comment by davidchenhs** [comment]
change Brushnet  end_at to 100~10000

**Comment by jokero3answer** [comment]
Thanks, it worked, what is the effect of this value range, what is the recommended value

**Comment by nullquant** [comment]
The value should be more than `steps` in KSampler. But if you need to BrushNet not be applied to some final steps, set it less. I will do an example for it and explain when it is needed soon.

**Comment by jokero3answer** [comment]
Thank you very much
