### ISSUE TITLE
When I try to run PowerPaint_outpaint, the workflow, this computer at work is working fine. But the one at my home, the command line message pops up after this paragraph and then it just keeps not moving And then it just keeps stopping moving. I don't know what it is.

### ISSUE THREAD

**Issue by jokero3answer** [nullquant/ComfyUI-BrushNet#76]
[rgthree] Using rgthree's optimized recursive execution.
clip missing: ['text_projection.weight']
PowerPaint base CLIP file:  D:\ComfyUI\models\clip\model.fp16.safetensors
Successfully add external embeddings: P_ctxt, P_shape, P_obj. current
Successfully add trainable external embeddings: P_ctxt, P_shape, P_obj current

It's going to get stuck at this node that I've circled in this red box and not move.
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/6bde88d4-ee46-426f-9230-505405191678)

help！！

**Comment by jokero3answer** [comment]
And the company's computer will be able to successfully execute below this red box

![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/d3135ca9-c1d6-41cc-81c2-bc42b9415893)
@nullquant

**Comment by nullquant** [comment]
It is stuck at loading PowerPaint CLIP stage. No errors? Strange, may be something wrong with `pytorch_model.bin` file?

**Comment by jokero3answer** [comment]
[Diagnostics-1715256083.log](https://github.com/nullquant/ComfyUI-BrushNet/files/15261920/Diagnostics-1715256083.log)
![image](https://github.com/nullquant/ComfyUI-BrushNet/assets/130854108/b6890bef-1a9b-4944-9573-6a94872fd2fd)

**Comment by jokero3answer** [comment]
It worked, re-downloaded and replaced the file and it's up and running, it's awesome!
