### ISSUE TITLE
Doesn't PowerPaint object removal support SDXL?

### ISSUE THREAD

**Issue by lzhfdwu007** [nullquant/ComfyUI-BrushNet#78]
As the title says, I get an error when using the SDXL model. It works fine when using SD1.5.

**Comment by nullquant** [comment]
No, PowerPaint model is only for SD1.5. There is no such model for SDXL and as far as I know authors don't plan to train it.

**Comment by lzhfdwu007** [comment]
Thank you for your answer THX

**Comment by nullquant** [comment]
No problem! :)
