### ISSUE TITLE
After outpainting, the original image becomes blurry。

### ISSUE THREAD

**Issue by lzhfdwu007** [nullquant/ComfyUI-BrushNet#79]
How can we keep the clarity of the original image in the new image?

**Comment by nullquant** [comment]
This is the nature of BrushNet. Please, see Blending inpaint example.

**Comment by lzhfdwu007** [comment]
Thank you very much for your reply. I did not find the workflow you requested in the example folder.
Could you please provide a workflow reference that can keep the original image clarity as unchanged as possible after OUTPAINTING?

**Comment by lzhfdwu007** [comment]
That's it. . .  but it doesn't seem to work for images with a height exceeding 1600PX after generation.

**Comment by lzhfdwu007** [comment]
Then there will be obvious straight lines at the seams. Is there a way to blend this out by adding a feathering effect?

**Comment by nullquant** [comment]
From README:

"...Sometimes inference and VAE broke image, so you need to blend inpaint image with the original: [workflow](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/example/BrushNet_inpaint.json). You can see blurred and broken text after inpainting in the first image and how I suppose to repair it..."

Also you shouldn't apply BrushNet to big images, as well as generating ones - too many artifacts, also UNet tends to copy things. You should work with 512x512 on SD1.5 and 1024x1024 on SDXL and then upscale it. Here is [workflow](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/example/BrushNet_SDXL_upscale.json).

**Comment by lzhfdwu007** [comment]
> From README:
> 
> "...Sometimes inference and VAE broke image, so you need to blend inpaint image with the original: [workflow](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/example/BrushNet_inpaint.json). You can see blurred and broken text after inpainting in the first image and how I suppose to repair it..."
> 
> Also you shouldn't apply BrushNet to big images, as well as generating ones - too many artifacts, also UNet tends to copy things. You should work with 512x512 on SD1.5 and 1024x1024 on SDXL and then upscale it. Here is [workflow](https://github.com/nullquant/ComfyUI-BrushNet/blob/main/example/BrushNet_SDXL_upscale.json).

Following this idea, if I want to enlarge a large-size image, should I first use the zoom node to reduce the size of the original image, then enlarge the image to the recommended size, and then upscale it? It will be better？

**Comment by lzhfdwu007** [comment]
Thank you, my doubts have basically been resolved! Thank you so much! ~~
