### ISSUE TITLE
cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet'

### ISSUE THREAD

**Issue by jarmud** [nullquant/ComfyUI-BrushNet#81]
The node is installed normally, and the process is displayed in red, indicating that it cannot function worked. It seems that there is a conflict in the environment configuration. But I can't see what the problem is.
python 3.1.0.11
xformers 0.03post1+cu118
torch 3.12+cu119
diffusers 0. 270

_**from diffusers.models.resnet import (
ImportError: cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet' (H:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\resnet.py)
Cannot import J:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-BrushNet module for custom nodes: cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet' (H:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\models\resnet.py)**_

**Comment by jarmud** [comment]
I fond diffusers 0.27.0 Not installed correctly

**Comment by lzqggghotmailcom** [comment]
解决了吗？

**Comment by jarmud** [comment]
> 解决了吗？

用其他整合包里的环境文件覆盖了就好了，pip 安装没用。

**Comment by ZHOUxiaohe1987** [comment]
方便上传一份环境文件么？

> > 解决了吗？
> 
> 用其他整合包里的环境文件覆盖了就好了，pip 安装没用。

**Comment by ZHOUxiaohe1987** [comment]
I has same problem :  anyone can help?
File "G:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet\brushnet\unet_2d_blocks.py", line 26, in
from diffusers.models.resnet import (
ImportError: cannot import name 'ResnetBlockCondNorm2D' from 'diffusers.models.resnet' (G:\AI\ComfyUI-aki-v1.3\python\Lib\site-packages\diffusers\models\resnet.py)

**Comment by jarmud** [comment]
> 方便上传一份环境文件么？
> 
> > > 解决了吗？
> > 
> > 
> > 用其他整合包里的环境文件覆盖了就好了，pip 安装没用。

我用的秋葉大佬整合包里python 里的的diff 文件夹

**Comment by nullquant** [comment]
`ResnetBlockCondNorm2D` class was added to `diffusers` at commit [`dd4459a`](https://github.com/huggingface/diffusers/commit/dd4459ad795230ee6d70dc270484bb9b523db9d4), Jan 10, 2024. The `diffusers` version at this time was `0.26.0.dev0`. So I added `0.27.0` version of `diffusers` in requirements. If you still have this problem it means you haven't updated this library in your ComfyUI's python installation. 

If you are using portable version of ComfyUI it has its own python installation and you should update `diffusers` library there. To do it you should open command line in your ComfyUI portable folder and do something like this:

`python_embeded\python.exe -m pip install -r ComfyUI\custom_nodes\ComfyUI-BrushNet\requirements.txt`
