### ISSUE TITLE
model Path is not compatible with extra_model_paths.yaml

### ISSUE THREAD

**Issue by amir84ferdos** [nullquant/ComfyUI-BrushNet#82]
when adding the inpaint folder to extra_model_paths.yaml then Brsuhnet can not load models

**Comment by nullquant** [comment]
Do you need this? Ok, I'll do it.

**Comment by nullquant** [comment]
Done. Try it, please.

**Comment by amir84ferdos** [comment]
yessss, it is working now :).
 thank you

**Comment by amir84ferdos** [comment]
would you please also check the **_CLIP_** node that is used with PowerPaint.
it does not use the Extra path

**Comment by nullquant** [comment]
SD1.5 text encoder model `model.fp16.safetensors` should be in `clip` folder of `extra_model_paths.yaml`, while `pytorch_model.bin` is in  `inpaint` folder of `extra_model_paths.yaml.

**Comment by amir84ferdos** [comment]
> SD1.5 text encoder model `model.fp16.safetensors` should be in `clip` folder of `extra_model_paths.yaml`, while `pytorch_model.bin` is in `inpaint` folder of `extra_model_paths.yaml.

I checked and the clip is not loading. Could you please check it? Only the clip is not working.
