### ISSUE TITLE
module 'comfy.samplers' has no attribute 'CFGGuider'

### ISSUE THREAD

**Issue by qingdengke88** [nullquant/ComfyUI-BrushNet#84]
<img width="261" alt="微信图片_20240513043208" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/169616938/c6aed661-6450-4bbe-a1b5-8a6c74d2fad6">
How should I resolve this error message after installation?

**Comment by nullquant** [comment]
Make sure your ComfyUI is updated, then, if the error persists, post you ComfyUI log with a list of custom_nodes.

**Comment by qingdengke88** [comment]
The issue has been resolved after updating COMFYUI to the latest version. Thank you very much

**Comment by nullquant** [comment]
No problem :)
