### ISSUE TITLE
BrushNet_cut_for_inpaint?

### ISSUE THREAD

**Issue by alenhrp** [nullquant/ComfyUI-BrushNet#88]
I don't see what the purpose of BrushNet_cut_for_inpaint is, please enlighten me!

**Comment by nullquant** [comment]
Let's suppose you work with a big image, say 4096 x 4096 pixels. And you want to inpaint an object with a mask 128 x 128 pixels. You can of course put the image directly to BrushNet node, but BrushNet's and base model preferred resolution is 512 x 512 (for SD1.5). The details on inpaint can be quite low quality if you get what you want at all. You can downsample the image in pixel space before BrushNet, but again the mask is too small compared to the image. 

`CutForInpaint` node cut off a part of image (512 x 512 by default - you can change it) around the mask at original resolution and then you insert cut part in BrushNet node, there is no downsampling and the size of mask is pretty big. After inpaint `BlendInpaint` node will add all together. As far as I know this is typical workflow for inpaint big images without BrushNet, so I added the node for usability.

There are two limitations. 
1. The size of the mask should be less than size of the cut off region (obvious).
2. BrushNet don't see the whole picture, so some important details for inpaint may be missing.
