### ISSUE TITLE
大佬，你能看看我这个报错吗

### ISSUE THREAD

**Issue by luckybananana** [nullquant/ComfyUI-BrushNet#89]
应该是5.10还可以正常使用的，后来一打开就产生了这个报错：Error occurred when executing KSampler:

Sizes of tensors must match except in dimension 0. Expected size 77 but got size 231 for tensor number 1 in the 
![微信图片_20240514191902](https://github.com/nullquant/ComfyUI-BrushNet/assets/141251585/c1e43468-0f73-41b3-8aeb-bdbfd5689c4c)

**Comment by nullquant** [comment]
Could you please post a complete ComfyUI log?

**Comment by zsmjts** [comment]
the same problem
<img width="1819" alt="PixPin_2024-05-16_10-27-23" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/126183834/5d2596aa-7972-45be-b8ff-f91dc056c044">

**Comment by nullquant** [comment]
I will look into the problem. What CLIP and what prompt do you use?

**Comment by luckybananana** [comment]
我找到了问题，我删减了一些提示词之后就可以继续跑起来了，之前提示词一多就会报错

**Comment by nullquant** [comment]
I find the bug with a long prompt. I hope it will work now.
