### ISSUE TITLE
Why does the brushnet loader reload when I've fixed the seed?

### ISSUE THREAD

**Issue by davidchenhs** [nullquant/ComfyUI-BrushNet#90]
I want to fix the image from Brushnet for further processing, but the brushnet loader doesn't seem to fix it and has to reload almost every time.

**Comment by nullquant** [comment]
Sorry, I don't understand your issue. Could you please post a log and workflow?

**Comment by davidchenhs** [comment]
The problem is not with brushnet. Sorry for causing trouble to you.
