### ISSUE TITLE
安装ComfyUI-BrushNet后前部节点都没了

### ISSUE THREAD

**Issue by lxingh** [nullquant/ComfyUI-BrushNet#91]
这次更新这个插件后, comfyui的全部节点都不能用了.删掉这个插件就正常了.也没有看到报错信息.10几天前这个插件还是正常的,昨天更新后就出现了这个情况. custom_nodes下删掉重新安装也没有用

![安装前](https://github.com/nullquant/ComfyUI-BrushNet/assets/1501974/7323ad23-7f7b-4472-9e40-f54177bc8738)
![安装后](https://github.com/nullquant/ComfyUI-BrushNet/assets/1501974/a0f81ea3-1603-4de3-b837-abd0de3311c7)
[comfyui(安装前).log](https://github.com/nullquant/ComfyUI-BrushNet/files/15316104/comfyui.log)
[comfyui(安装后).log](https://github.com/nullquant/ComfyUI-BrushNet/files/15316102/comfyui.log)

**Comment by luoweiyi** [comment]
same problem

**Comment by nullquant** [comment]
So, did I understand correctly that when you install ComfyUI-BrushNet, ComfyUI loses all installed nodes? Without any errors? This is weird. I am not sure how this is possible, but we can try this: you can revert back to any previous version of BrushNet and see is it work. [Here](https://github.com/nullquant/ComfyUI-BrushNet/commits/main/) you can see all commit history. At the right side there is a hex number of commit. To go back in time you open a `cmd` in `custom_nodes/ComfyUI-BrushNet` folder and execute, for example, `git checkout 3715546`. This will move ComfyUI-BrushNet to version before image batch implementation.

Please, post you results.

**Comment by luoweiyi** [comment]
> So, did I understand correctly that when you install ComfyUI-BrushNet, ComfyUI loses all installed nodes? Without any errors? This is weird. I am not sure how this is possible, but we can try this: you can revert back to any previous version of BrushNet and see is it work. [Here](https://github.com/nullquant/ComfyUI-BrushNet/commits/main/) you can see all commit history. At the right side there is a hex number of commit. To go back in time you open a `cmd` in `custom_nodes/ComfyUI-BrushNet` folder and execute, for example, `git checkout 3715546`. This will move ComfyUI-BrushNet to version before image batch implementation.
> 
> Please, post you results.

i find reason, 
my extral_model_paths.yaml :   inpant: /path/to/inpaint/
with an extra / symbol at the path end
and the function get_files_with_extension stuck at the while loop,
when i change to inpant: /path/to/inpaint, everthing goes well
so, i think it's bug~

**Comment by nullquant** [comment]
Thank you very much! I just did a quick fix.

**Comment by lxingh** [comment]
谢谢!现在重新安装正常了.
