### ISSUE TITLE
Brush net loader node doesn't have the actual model and can't find the file

### ISSUE THREAD

**Issue by rongtian0927** [nullquant/ComfyUI-BrushNet#94]
Inside my brushnet loader node, it only have model MAT and Foocus, and I can't find the file to put in the actual model, I am using the Rundiffusion, can someone help me on this issues?

**Comment by nullquant** [comment]
Did you download BrushNet models to `models/inpaint` folder? I have no experience with Rundiffusion, does it have analog of `extra_model_paths.yaml`?
