### ISSUE TITLE
After upgrading to the latest version, 'inpainting mode' doesn't work properly anymore

### ISSUE THREAD

**Issue by cdmusic2019** [nullquant/ComfyUI-BrushNet#96]
BrushNet model does not load properly and displays: BrushNet inference: do_classifier_free_guidance is True False
![01](https://github.com/nullquant/ComfyUI-BrushNet/assets/126891037/72f980ef-7f2b-4c58-88b4-8973926b8960)
![02](https://github.com/nullquant/ComfyUI-BrushNet/assets/126891037/9459a171-2fa6-4256-9f6a-94c222945ffc)
Does anyone know how to fix this please, thanks.

**Comment by nullquant** [comment]
Set end_at parameter in BrushNet node to number higher than 10 = number of steps in KSampler. In your case BrushNet is applied for first step only.
