### ISSUE TITLE
Am I getting it wrong?

### ISSUE THREAD

**Issue by JaviSt97** [nullquant/ComfyUI-BrushNet#97]
Hello savvy diffusers,

I've been playing around with the nodes. Having some relative success in certain cases, but I'm pretty much stuck at this:
 
<img width="500" alt="image" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/162743219/459d9faa-28a5-427c-88e8-f92289c0acb1">

For some reason all the results I get are burnt, but I'm pretty sure of using the same settings as other (great) results I've seen out there. Any idea what could be causing this ?

- Happens both with brushnet segmentation and mask
- Across all brushnet scale levels (0.8 seem to show a bit more prompt understanding..)
- I've resorted to the cut for inpaint node, thinking my 1024x1024 image might have been the problem. But nothing..
- Tried different ckpts, but mainly on Juggernaut X + Euler A

Any idea what's going on there ? Below the worflow
<img width="300" alt="image" src="https://github.com/nullquant/ComfyUI-BrushNet/assets/162743219/e44c4b64-e168-4050-8424-b3d3f6bf3182">

**Comment by nullquant** [comment]
Well, you have here a very difficult task. First, BrushNet likes to inpaint objects not empty spaces, second you have roof supports which resembles palm tree - BrushNet tries to create it along this dome. But the main error is your mask. You should think of BrushNet as a certain type of ControlNet and its mask as a contour of object you try to inpaint. When you have empty scene as a result it means BrushNet could not imagine your prompt in that mask or tried to create it somewhere else.

So, I changed a mask and prompt, and here is a palm leaf, not so beautiful though:

![Screenshot from 2024-05-17 13-18-51](https://github.com/nullquant/ComfyUI-BrushNet/assets/81931994/c2aec5c3-da5a-4eca-9eab-133b8cd493f7)

**Comment by JaviSt97** [comment]
You legend ! Thank you, that's definitely sharpening my intuition on how to better handle the model.

Probably working on a mocked up collage will give a batter base for brushnet to work with, and from there some latent upscaling to make smooth out details.
