### ISSUE TITLE
Symlink of models not working

### ISSUE THREAD

**Issue by SoaringTiger** [nullquant/ComfyUI-BrushNet#98]
My symlink directory structure is as follows in inpaint path
```
powerpaint -> /workspace/storage/stable_diffusion/models/inpaint_brushnet/powerpaint
sd1.5_random_mask -> /workspace/storage/stable_diffusion/models/inpaint_brushnet/sd1.5_random_mask
sd1.5_seg_brushnet_ckpt -> /workspace/storage/stable_diffusion/models/inpaint_brushnet/sd1.5_seg_brushnet_ckpt
xl_random_mask -> /workspace/storage/stable_diffusion/models/inpaint_brushnet/xl_random_mask
xl_seg_mask -> /workspace/storage/stable_diffusion/models/inpaint_brushnet/xl_seg_mask
```
They cannot be recognized by the Loader node.
If I move the files into inpaint path, they are working.

**Comment by zhongdi** [comment]
so do i

**Comment by nullquant** [comment]
Symlink of folders is not a good idea - it can create infinite loops and it already does in some people issues, symlink of files should work.

**Comment by SoaringTiger** [comment]
> Symlink of folders is not a good idea - it can create infinite loops and it already does in some people issues, symlink of files should work.

I moved all symlinks to the inpaint path, works fine👍
